### PR TITLE
More help?

### PR DESCRIPTION
**Pull request by HeyAri**
Heya, did I mention Ari is hebrew for lion?

Anyway, email is working but it is sending a blank email. Do we need to do something to grab the fields used in the certificate?
I tried a bunch of stuff but nothing worked. Could have been my syntax though. Do I need another $post inside the email php?

One other thought for email is to send the entire certificate as an image, maybe as a pdf?

Also I need an opinion. I read a couple options to get backgrounds to print. One was using HTML to display the table and CSS to call the print including the background. Another option I was wondering about is using inline divs and z index? Not sure exactly how to code either yet, but thought those might be two options.

Thanks again for your help!

### CODE REVIEW

**Comment by shadowlion** [comment]
I would suggest using a different PHP mail packager other than the native PHP. Take a look at this one <https://github.com/PHPMailer/PHPMailer>. I use this in my commercial products and it works quite well. You would use $_POST[‘email’] input from the form to give you the value on certificate.php and you can use that variable freely. 

I would say a pdf would be the best option; you could make it such that you only preview the certificate on the site, but then create a Download button so they download the result as a pdf. This way, it would take care of the print problem.

Inline-divs might work, but z-index isn’t necessary because it only applies to stacking elements on top of each other.

**Comment by HeyAri** [comment]
Thanks, question, should I replace the code in the certificate page with phpmailer code or should I put it on the index page? I tried messing around with it before I met you and couldn't get it to work.

Ari
513.348.9120

On Jun 4, 2017, at 4:41 PM, Justin Chiou <notifications@github.com<mailto:notifications@github.com>> wrote:

I would suggest using a different PHP mail packager other than the native PHP. Take a look at this one <https://github.com/PHPMailer/PHPMailer>. I use this in my commercial products and it works quite well. You would use $_POST[‘email’] input from the form to give you the value on certificate.php and you can use that variable freely.

I would say a pdf would be the best option; you could make it such that you only preview the certificate on the site, but then create a Download button so they download the result as a pdf. This way, it would take care of the print problem.

Inline-divs might work, but z-index isn’t necessary because it only applies to stacking elements on top of each other.

**Comment by shadowlion** [comment]
I’ll get you a pull request by tonight so you can see how it works - you’ll have to configure some of the finer details once merged.

**Comment by HeyAri** [comment]
Thanks for your help!


On Jun 4, 2017, at 8.16 P, Justin Chiou <notifications@github.com<mailto:notifications@github.com>> wrote:

I’ll get you a pull request by tonight so you can see how it works - you’ll have to configure some of the finer details once merged.

**Comment by shadowlion** [comment]
See the pull request -

- Details will need to be added in such that the sender and emailer details are correct 
- you can also play around with it such that we can add file attachments
- best process would probably be finding a way to compile the certificate to a pdf/jpeg, save as a temporary file, fire the php mailer to add it as an attachment, and then destroy the temporary file.

**Pull request merged**
