### PR TITLE
Revert "Add files via upload"

### PR DESCRIPTION
**Pull request by HeyAri**
Reverts HeyAri/Certify-Yourself-Working-directory#5

### CODE REVIEW

**Comment by shadowlion** [comment]
Are you not gonna use the PHPMailer from the earlier merge?

**Comment by HeyAri** [comment]
I may have messed stuff up. Yes, I am using what you set up for mail. Should I email you the actual certificate.PHP?

Ari
513.348.9120

On Jun 7, 2017, at 4:51 PM, Justin Chiou <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you not gonna use the PHPMailer from the earlier merge?

**Comment by shadowlion** [comment]
You don't have to; I was looking at the merge request, and it looked like if you merge it, you'd be losing the code necessary to use phpmailer. Lemme take another look at it before letting you know what to do with this request; I think you just forgot to fetch the new data after merging.

**Comment by shadowlion** [comment]
From what is there currently, you merged the right file over, but then committed a snapshot that didn’t have the new stuff; You’ll have to roll back your commit before you have the right set of files.

All the Best,

Justin Chiou
chiou.kai@gmail.com
630-204-8122
justinchiou.me

**Comment by HeyAri** [comment]
Oy. I thought I rolled it back. Maybe I can start a new fork?

Ari
513.348.9120

On Jun 7, 2017, at 7:57 PM, Justin Chiou <notifications@github.com<mailto:notifications@github.com>> wrote:

From what is there currently, you merged the right file over, but then committed a snapshot that didn’t have the new stuff; You’ll have to roll back your commit before you have the right set of files.

All the Best,

Justin Chiou
chiou.kai@gmail.com<mailto:chiou.kai@gmail.com>
630-204-8122
justinchiou.me<http://justinchiou.me>

**Comment by HeyAri** [comment]
I think I have it reverted now?

**Comment by shadowlion** [comment]
Kinda - you have a branch called “revert-5-…” which has the wrong changes. I would checkout the master branch to get the current stuff, and then delete all other branches so we can sorta hit a reset button on it all - and then create a new branch with your experimental changes.

All the Best,

Justin Chiou
chiou.kai@gmail.com
630-204-8122
justinchiou.me

**Comment by HeyAri** [comment]
I started a new repository - https://github.com/HeyAri/Center-4-Certification

It has some bad test files from testing options like JustinMind to make the divs work so just ignore those…

**Comment by shadowlion** [comment]
I think you’ve only made changes on the local level - you want me to populate it with the current code?

All the Best,

Justin Chiou
chiou.kai@gmail.com
630-204-8122
justinchiou.me

**Comment by HeyAri** [comment]
Sure. Did I mess up the new repository too?

**Comment by shadowlion** [comment]
Well, you haven’t created any files in it, so there’s no branch to merge into. If you’re gonna let me in on this project (rather than forking it), you’ll have to add me as a collaborator in the settings page.

All the Best,

Justin Chiou
chiou.kai@gmail.com
630-204-8122
justinchiou.me

**Comment by HeyAri** [comment]
Sure thing. I'll add you in a couple hours. I'm out running the kids to school and stuff.

Thanks!

Ari
513.348.9120

On Jun 8, 2017, at 7:31 AM, Justin Chiou <notifications@github.com<mailto:notifications@github.com>> wrote:

Well, you haven’t created any files in it, so there’s no branch to merge into. If you’re gonna let me in on this project (rather than forking it), you’ll have to add me as a collaborator in the settings page.

All the Best,

Justin Chiou
chiou.kai@gmail.com<mailto:chiou.kai@gmail.com>
630-204-8122
justinchiou.me<http://justinchiou.me>

**Comment by shadowlion** [comment]
Sure thing!

All the Best,

Justin Chiou
chiou.kai@gmail.com
630-204-8122
justinchiou.me

**Pull request closed without merging**
